[package]
name = "license-generator"
version = "0.1.0"
authors = ["azu <azuciao@gmail.com>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
[dependencies]
license = "0.7.2"
structopt = "0.2.14"
chrono = "0.4"